### PR TITLE
Update hypertext reference for External link and externalLinks.html versioning to v2.0

### PR DESCRIPTION
**Pull request by AndiAJ**
• Update versioning for `externalLinks.html` to v2.0
• Update hypertext reference to `mozilla-mobile.github.io/testapp/downloads` for External link.

### CODE REVIEW

**Comment by AaronMT** [comment]
@AndiAJ We'll want to copy the entire project into `v2.0` so it's all available, and check paths that everything works. For new versions, for review, I think we'll want to do 2 commits (1 that copies everything into a new `v.x.`) and a commit with the intended updated changes for clarity in review to see what's new.

Aside, why are we changing this from Google to Duckduckgo?

**Comment by AndiAJ** [comment]
> @AndiAJ We'll want to copy the entire project into `v2.0` so it's all available, and check paths that everything works. For new versions> 

Synced up with @sv-ohorvath yesterday and agreed that:
We don't think we should move the entire project into `v2.0` because we'll update the versioning for pages that weren't changed at all.
We think it would be better to only copy the page/pages in question to a new directory.

> for review, I think we'll want to do 2 commits (1 that copies everything into a new `v.x.`) and a commit with the intended updated changes for clarity in review to see what's new.
> 
Sounds good.

> Aside, why are we changing this from Google to Duckduckgo?

There are 2 reasons to use another search provider:
• Google is sometimes blocking our requests, read an article that duckduckgo could be the solution to overcome the "unusual traffic" problem.
image

• When we run the UI tests locally for Beta or RC builds, we always need to manually dismiss Google's cookie consent 

@sv-ohorvath [suggested to use  one of the testapp pages](https://github.com/mozilla-mobile/fenix/pull/25173#discussion_r874570904) so I've changed the hypertext reference to mozilla-mobile.github.io/testapp/downloads for "External link"

@AaronMT please review and share your thoughts.
**P.S. please don't merge the PR because I'll need to change the links in the tests as well.**

**Comment by AaronMT** [comment]
Hi @AndiAJ @sv-ohorvath, I spoke with Richard and we think that copying the entire project into a `v2.0` and then-forth new versions is simple enough that is copies the snapshot paradigm. Space is not an issue and since this app is so simple in that regard it's fine.  For this bug, can you create a new commit that copies the entire project (you can exclude `README` `CODE_OF_CONDUCT` and `LICENSE`) into a `v2.0` directory, so final URL will be https://mozilla-mobile.github.io/testapp/v2.0/externalLinks.html with https://mozilla-mobile.github.io/testapp/externalLinks.html treated as a `v1.0`

**Comment by AndiAJ** [comment]
Made the changes @AaronMT , let me know if it's ok . ☺️

**Review by AaronMT — APPROVED** [review]

**Pull request merged**
