### PR TITLE
Adds new downloads test page and assets.

### PR DESCRIPTION
**Pull request by sv-ohorvath**
@AaronMT @rpappalax Does this look okay? Would you rather like the assets to be in a separate folder? I followed the current structure but I can organize them better if you'd like.

Removed local resources. 

Linked files from GCP.

### CODE REVIEW

**Comment by rpappalax** [comment]
@sv-ohorvath a separate folder called /downloads may be a bit cleaner if you have time to do it

**Comment by sv-ohorvath** [comment]
> @sv-ohorvath a separate folder called /downloads may be a bit cleaner if you have time to do it

@rpappalax I already did, but I called it resources. Would you like me to rename it?

**Comment by AaronMT** [comment]
lgtm (I can't formally review this repo)

**Comment by rpappalax** [comment]
> 

resources or downloads is OK.  My only ask would be to update the README to indicate that you're pulling resources from a remote GCP bucket due to their file size (Unless @AaronMT wants to document all of the test page stuff in a different location).

**Pull request merged**
