### PR TITLE
Clock and Calendar PWA form

### PR DESCRIPTION
**Pull request by AndiAJ**
New date and time picker test page.

Used the page created on my repo https://andiaj.github.io/testapp/clockAndCalendarForm.html and works properly with the newly created smoke tests: `cancelCalendarFormPWATest` `setAndClearCalendarFormPWATest`, `cancelClockFormPWATest` `setAndClearClockFormPWATest `

• The PWA is properly installed
• Both the date and time pickers can be properly used
• The selected options are properly printed after tapping the submit date/time buttons

### CODE REVIEW

**Review by AaronMT — COMMENTED** [review]
Can we add this to the existing index page? I don't think we need a create a separate forms page, unless there's complications with scrolling down the page for now. If so, we might want to create a basic elements page.

**Comment by AndiAJ** [comment]
Hi @AaronMT , thanks for your review.

Indeed, scrolling is the main problem.
I've added everything to https://andiaj.github.io/testapp/htmlControlsForm.html (external links, logins form, date and time picker)
Updated the tests as well and everything seems to be working properly.

Let me know what you think, thanks!

**Comment by AndiAJ** [comment]
Also, added a color picker to the page.

**Comment by AndiAJ** [comment]
Added a drop-down form

**Comment by AaronMT** [comment]
We might want to make this a local asset instead based on conversations

**Comment by AndiAJ** [comment]
Hey @AaronMT I've continued to add missing controls and also created new PWA UI tests which seem to work properly.

We already have tests that work perfectly using the test app web-page and has a great potential to help use increase UI test coverage.

@sv-ohorvath explained why it's not feasible to use local assets for PWA's [here](https://mozilla.slack.com/archives/C02KDDS9QM9/p1643881784471039?thread_ts=1643880665.471959&cid=C02KDDS9QM9)

**Comment by AaronMT** [comment]
Hi @AndiAJ I reverted this merge because there are tests that still use the deleted files, are those updated somewhere?

**Comment by AaronMT** [comment]
We will need to open a re-open this as a new PR

**Comment by AndiAJ** [comment]
> Hi @AndiAJ I reverted this merge because there are tests that still use the deleted files, are those updated somewhere?

Yes, in the PR's containing the tests, but to be 100% sure everything looks good, I'll recheck everything.

> We will need to open a re-open this as a new PR

Sounds good, thank you! ☺️

**Pull request merged**
